name: Deploy Flask App to GitHub Pages

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - master  # Adjust to match your default branch, e.g., main or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust to match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set Firebase credentials
        env: 
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: echo "FIREBASE_CREDENTIALS='$FIREBASE_CREDENTIALS'" >> $GITHUB_ENV

      - name: Update SERVER_NAME in main.py
        run: sed -i "s|app.config['SERVER_NAME'] = 'localhost:5000'|app.config['SERVER_NAME'] = 'godstark82.github.io'|" main.py

      - name: Run freeze script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python freeze.py

      - name: Adjust base href
        run: sed -i 's|<base href="/">|<base href="/journal_web/">|' build/index.html
      - name: Update SERVER_NAME in main.py
        run: sed -i "s|app.config['SERVER_NAME'] = 'localhost:5000'|app.config['SERVER_NAME'] = 'flixstar.shop'|" main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Frozen-Flask will output the static files here
